# permissions for end users to edit colonies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: colony-editor-role
rules:
- apiGroups:
  - abc-optimizer.pesu.edu
  resources:
  - colonies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - abc-optimizer.pesu.edu
  resources:
  - colonies/status
  verbs:
  - get
