---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - abc-optimizer.pesu.edu
  resources:
  - colonies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - abc-optimizer.pesu.edu
  resources:
  - colonies/finalizers
  verbs:
  - update
- apiGroups:
  - abc-optimizer.pesu.edu
  resources:
  - colonies/status
  verbs:
  - get
  - list
  - patch
  - update
